# -*- coding: utf-8 -*-
"""3_19301261_IshraqAhmedEsha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GS1-sD1GsPel4X0XIe8HwTUJ7U8lZNik

TASK 1
"""

#TASK 1

import math 
import random

st_id = input("Enter your student ID: ")
rr, a, b, d, val = int(st_id[4]), int(st_id[6]), int(st_id[7]), int(st_id[3]),[]
RR = int(rr)

r_a, r_b = str(a), str(b)

rx = int(r_b + r_a)
RX=int(int(rx) * 1.5)

def minMax(n, ra_idx, gg, val, r_l, r_t):
  if n == 3:
    return val[ra_idx]
  if gg:
    rst = RR
    for i in range(0,2):

      value = minMax(n+1, ra_idx*2+i, False, val, r_l, r_t )
      rst = max(rst, value)
      r_l = max(r_l, rst)
      if r_t <= r_l:
        break
    return rst
  else:
    rst = RX
    for i in range(0,2):
      value = minMax(n+1, ra_idx*2+i, True, val, r_l, r_t)
      rst = min(rst, value)
      r_t = min(r_t, rst)
      if r_t <= r_l:
        break
    return rst

for i in range(8):
  e = random.randint(RR, RX)
  val.append(e)

print("Generated 8 random points between the minimum and maximum point limits:", val)
print("Total points to win:", rx)
print("Achieved point by applying alpha-beta pruning =", minMax(0,0,True, val,RR,RX))
if minMax(0,0,True,val,RR,RX) >= rx:
  print("The winner is Optimus Prime")
else:
  print("The winner is Megatron")
print()

"""TASK 2

"""

#TASK 2

print("After the shuffle: ")
l, c = [],[]
for i in range(len(d)):
  random.shuffle(val)
  r = minMax(0,0,True, val, RR, RX)
  l.append(r)
print("List of all points values from each shuffles:", l)
for i in l:
  if i >= rx:
    c.append(i)

def bigger(array, e):
  max = array[0]
  for i in range (1, e):
    if array[i] > max:
      max = array[i]
  return max

e = len(c)
final_rst = bigger(c, e)
print("The maximum value of all shuffles:", final_rst)
print(r"Won {e} times out of {d} number of shuffles")